// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/redux-immutable/redux-immutable.d.ts
// Type definitions for redux-immutable v3.0.5
// Project: https://github.com/gajus/redux-immutable
// Definitions by: Pedro Pereira <https://github.com/oizie>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

declare module "redux-immutable" {
    export function combineReducers(reducers : Object): any;
}
